name: 🙋 Question
description: Ask a question here
title: 🙋 <question title>
labels: question

body:
  - type: textarea
    attributes:
      label: Description
      placeholder: >-
        A clear and concise description of what you question is about...
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: What has to change & What we can do to resolve your question
      placeholder: >-
        Any alternative solutions or features you've considered...
    validations:
       required: true

  - type: textarea
    attributes:
      label: Additional Context
      placeholder: >-
        Any other context or considerations about the question...
      
  - type: textarea
    attributes:
      label: Screenshots
      placeholder: >-
        If applicable, please provide relevant screenshots or screen recordings...
        
  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing question for this?
      description: Please search to see if an issue already exists for the question you encountered.
      options:
      - label: I have searched the existing issues
        required: true